### PR TITLE
Move add_accumulator_to_context to ToFieldStep

### PR DESCRIPTION
**Pull request by cbeer**
I'm thinking this may be an easy way to open up traject to support things like:

https://github.com/billdueber/indexing_thoughts/blob/master/old_readme.md#thought-1-pass-around-capsules

and allow me to extend traject in my local application to support things like single-valued fields.

### CODE REVIEW

**Comment by cbeer** [comment]
I've fixed the build in #146.

**Comment by jrochkind** [comment]
seems reasonable to me.

**Comment by billdueber** [comment]
That'll teach me to leave my scratch notes where people can find them. 

Looks good to me, too. Any reason to believe we can't just fold it in?

**Comment by jrochkind** [comment]
just moving the method from one object to another? I...  don't think so?  I haven't gotten my head around the motivation, but the move seems a rational one, it probably should have been in the new place in the first place. I don't think this is in any sense a public API?

**Comment by cbeer** [comment]
bump?

**Pull request merged**
