### PR TITLE
Adds XML example and sample data file

### LINKED ISSUE #264: Example on how to process and XML file
I wanted to add a small but complete example on how to parse an XML file (https://gist.github.com/hectorcorrea/59fa5854ce6f9ee1a4b86a23fea5f108) but I am not sure if this is something you are interested in and/or where to put such example. 

This would be to complement the notes already existing in [xml.md](https://github.com/traject/traject/blob/master/doc/xml.md) 

Any thoughts?

### PR DESCRIPTION
**Pull request by hectorcorrea**
Here is a first pass at adding an XML example including a sample MARC XML file.

Fixes #264

### CODE REVIEW

**Comment by jrochkind** [comment]
Hm, I didn't pay close enough attention and didn't realize it was a Marc XML file, sorry missed that. 

You can of course use the "Marc" configuration to read MarcXML, and get access to the all marc-specific logic that's in there, like the `extract_marc` macro. And configuration files that will work whether your input is Marc21 or MarcXML. 

While you *can* use the generic XML path for MarcXML, with generic XML functions like `extract_xpath`.... is there a particular reason you are chosing to?

To me procesing MarcXML with XML path instead of Marc path seems like an unusual non-recommended thing to do, so I'm cautious of making it the main XML example. I feel like it will risks some people find it and thinking you have to use the XML path with MarcXML, or that we recommend you do that. Which I don't think we do?

**Comment by hectorcorrea** [comment]
My bad. When trying to use `extract_marc` I got an error saying: 

```
NoMethodError:undefined method `extract_marc' for #<Traject::Indexer::NokogiriIndexer:0x00007fdbecb1acb8>
Did you mean?  extract_xpath
```

so I assumed that the "normal" MARC functions were no available, but it seems that I am mistaken. Let me take a closer look and reach back.

**Comment by jrochkind** [comment]
oh okay cool. yeah, it should work, that's a different problem!  Not sure what. But yeah people were using traject with MarcXML in Marc mode before traject even *had* an XML mode. 

This may be a different documentation bug, if it wasn't clear that marc mode *should* support MarcXML too?

Plus possibly some technical problem you were running into.

**Comment by jrochkind** [comment]
Based on the error, somehow you have configured traject in "XML" mode -- which basically just means using the Traject::Indexer::NokogiriIndexer.  Which the error message shows you are doing. 

And indeed that mode/indexer subclass doens't have an extract_marc. 

You triggered that by `-i xml`. If you hadn't done `-i xml`, the default (partially for legacy backwards compat purposes) is Marc mode with a Marc indexer, where you should have `extract_marc`. 

If the docs misled you and we can figure out how to maek them more clear, I'm interested!

**Comment by hectorcorrea** [comment]
@jrochkind thank you very much for the feedback. This makes much more sense now. 

I've updated the example to use the correct syntax to detect the MARC XML file and to extract data with the regular `extract_marc` function. 

I was confused initially because the XML file that I was parsing did not have namespaces (thanks Alma) and it was not very clear to me what the problem was so I ended up going the wrong way about it. 

The XML file that I am including in this PR has namespaces to show the "happy path" and not complicate things.

**Comment by jrochkind** [comment]
I'm glad you got straightened out!

## Your original problem

I wonder if we could use better error messages for when it is trying to recognize the file as MarcXML but fails to? Maybe that could have gotten you straightened out quicker?  It's not clear to me what happened when you tried to process the MarcXML without namespaces -- I guess it just didn't find any records? Hm, I'm not sure what the error message would be... I guess MarcXML normally *only* contains marc documents, so it it doesn't find any but DOES find *other* XML entities it doesn't recognize, it could at least print out a warning somewhere?

Or our docs could be more clear about what the MarcXML reader can recognize as MarcXML, what the MarcXML standard is? Now that we know there are common vendor softwares that say they output MarcXML but it's not compliant with the standard. 

And another option, we could provide a configuration option in the MarcXML reader to ignore namespaces in a way that makes it work for alma?

## This PR, and docs

I don't think this Marc example belongs in the xml.md file -- that doc file is really about XML mode, not marc mode. 

Now that we understand where you were getting into trouble... do you still think we need a full MarcXML example at all like this?

If so, I think I'd just put it in `./examples/marc` or `./examples/marcxml` maybe? Definitely not in `./examples/xml` or the `xml.md` doc file. 

There isn't a separate marc.md doc file, because that is covered in the README. Kind of for legacy reasons, when traject started all it did was marc. 

I definitely don't want to doc MarcXML examples in the "XML" docs -- those docs are about `-i xml`, doc'ing MarcXML processed in MARC mode there furthers the confusion you were originally under, that MarcXML needs to be or is recommended to be processed with traject's XML mode.

**Comment by jrochkind** [comment]
Quoting myself:

> And another option, we could provide a configuration option in the MarcXML reader to ignore namespaces in a way that makes it work for alma?

Since Alma is popular software, that seems like maybe a useful thing?  if you're interested in PR'ing that? Or if you make a PR that just has a failing test with Alma-style MarcXML and trying to read it and it not working -- I can probably flesh in the code with a configuration option to make the test pass.

**Comment by hectorcorrea** [comment]
I added a short notice to xml.md to indicate that this documentation is not meant for parsing MARC XML. I thing that is one of the things that threw me off: I saw a XML specific page and I just assumed that's how I should proceed.

I moved the sample MARC XML file to ./examples/marc/tiny.xml as you suggested.

I added the complete example to the README.md file since I thought it would be helpful for people to have a way to run Traject with a sample file.

I'll add a separate issue for the problems parsing MARC XML files without namespaces.

**Comment by jrochkind** [comment]
OK, merging (finally!), thank you @hectorcorrea !

**Pull request merged**
