### PR TITLE
For 3.0: update ruby versions supported

### PR DESCRIPTION
**Pull request by jrochkind**
MRI >= 2.2, jruby >= 9.0.  Drop jruby 1.7 and earlier MRI.

### CODE REVIEW

**Comment by jrochkind** [comment]
I noticed Nikitas Tampikas (apparently no github account?) said in a listserv post that they're still using JRuby 1.7.  Those Jruby errors are mysterious to me (and all tests pass in Jruby 9k). I myself no longer use Traject at my day job. 

Does anyone think it will be a problem to support only JRuby 9.0+ in traject 3.0? I'd really like to use ruby features only available in MRI 2.1+, which JRuby 9.0 is compatible with, but JRuby 1.7 is not.

**Comment by jrochkind** [comment]
I noticed Nikitas Tampakis (@tampakis) said in a listserv post that they're still using JRuby 1.7.  Those Jruby errors are mysterious to me (and all tests pass in Jruby 9k). I myself no longer use Traject at my day job. 

Does anyone think it will be a problem to support only JRuby 9.0+ in traject 3.0? I'd really like to use ruby features only available in MRI 2.1+, which JRuby 9.0 is compatible with, but JRuby 1.7 is not.  @billdueber

**Comment by jrochkind** [comment]
(Also failing MRI 2.5 for annoying rubygems bug interacts with travis reasons, will deal with it later if travis doesn't fix it somehow).

**Comment by jrochkind** [comment]
So far I have avoided writing any code that requires ruby 2.0+, because we haven't resolved this issue. 

The most obvious inconvenience is being unable to use new-style keyword arguments, having to do the `options = {}` thing. 

There are other conveniences that aren't occurring to me now. 

It can definitely be done, it's just kind of a pain, for a version of ruby that is well past end-of-life and no longer even receiving updates for major security vulnerabiltiies.  We can do it if we need to, but I'd definitely appreciate you trying to discover a bit more about the nature of the problems you were having, before we do that.  We won't drop support for any versions except on a major version release, which will be rare, so the 3.0 release I'm working on now would be a great time to drop some of this cruft.

**Comment by jrochkind** [comment]
@tampakis have you had a chance to see if recent jruby 9k releases still give you problems, or learn anything more about your problems?

It looks like JRuby 1.7 is offiically out-of-support as of November. https://github.com/jruby/jruby/issues/4112#issuecomment-346190422

**Comment by jrochkind** [comment]
Gah, running _locally_ on ruby 2.5.0, the test suite actually produces an interpreter crash with a core dump. `/Users/jrochkind/.gem/ruby/2.5.0/gems/marc-1.0.2/lib/marc/xml_parsers.rb:179: [BUG] Stack consistency error (sp: 146, bp: -566524928)`. 

Trying to investigate what's going on.

**Comment by jrochkind** [comment]
Error in MRI 2.5 seems to be an actual bug in MRI 2.5 that causes a crash and core dump. 

ruby-marc in REXML mode triggers it, reported at https://github.com/ruby-marc/ruby-marc/issues/53

Narrowed down to a reproduction without ruby-marc involved, reported to ruby at: https://bugs.ruby-lang.org/issues/14403

**Comment by tampakis** [comment]
@jrochkind we have updated our indexing routine to use MRI so we won't need 1.7 support anymore.

**Comment by jrochkind** [comment]
ok, thanks for the update @tampakis! 

Did you find much slowdown with MRI?

**Pull request merged**
