### PR TITLE
allow hashie 5.x

### LINKED ISSUE #280: Allow hashie 5.0
We have a regrettable dependency on hashie. Hashie 5.0 has been released, but our gemspec does not yet allow it. 

Presumably all tests will pass for our relatively limited uses of hashie, and we can just update gemspec. 

https://github.com/hashie/hashie/blob/master/CHANGELOG.md#500---2021-11-08

### PR DESCRIPTION
**Pull request by jrochkind**
Closes #280

### CODE REVIEW

**Comment by jrochkind** [comment]
Should a release with only this change be minor or patch? @billdueber ?

**Comment by billdueber** [comment]
I think the supposedly-breaking change is probably this one:

```
#521: Do not convert keys that cannot be represented as symbols to String in Mash initialization
```

This, sadly, _is_ a breaking change in that it will no longer convert any old key to a string. Normally not an issue, but I would be we've got people passing in things like `Pathname` objects somewhere out there in the wild. 

God, I hate to waste a major version on it, but I think we probably gotta.

**Comment by jrochkind** [comment]
Aha. This change in Hashie: https://github.com/hashie/hashie/pull/521

We are not using the `Mash` class, so it may not apply to us? Our use of Hashie is pretty targetted, just:

https://github.com/traject/traject/blob/f8e802f3fae03e7f5180cfb95f38febc961664a2/lib/traject/indexer/settings.rb#L26-L32

(We also have our own monkey-patch to traject at https://github.com/traject/traject/blob/f8e802f3fae03e7f5180cfb95f38febc961664a2/lib/traject/hashie/indifferent_access_fix.rb)

We *do* use the `Hashie::Extensions::IndifferentAccess` mixin, which seems related to this functionality... but do not actually use `Mash`.  Does the change only apply to Mash?  If so, it doesn't apply to us? Hard to say. Am not confident from the Hashie PR diff. 

If it does apply to us.... it doesn't make any tests fail.  If I had a failing test, I'd still avoid a major release by just putting some code into traject that checks Hashie version and adds some custom code for Hashie 5 to make it backwards compat (possibly using new Hashie 5 mix-in). 

But we don't have a reproduction of anything actually breaking... my inclination is to act assuming it doesn't apply to us. If anyone reports a bug, we can fix it then. I think chances are slim it will affect anyone. (and of course if a local project *knows* it applies to them, they can always lock to an older Hashie, we aren't ceasing to support the old Hashie here.  Agree it would be bad for them to find out the hard way though). 

Thoughts @billdueber ?

**Comment by jrochkind** [comment]
Looking/thinking/letting it sink in further, I think it really is just about Mash, which we don't use. "This PR changes the initialization behavior of Mash" -- yeah, we don't use that.

**Comment by jrochkind** [comment]
Gah, on the other hand:

> the changes here address an existing bug where any Hash extended with Hashie::Extensions::SymbolizeKeys or Mash extended with Hashie::Extensions::Mash::SymbolizeKeys

So that's not just mash... we don't use `Hashie::Extensions::SymbolizeKeys`, but do use `Hashie::Extensions::IndifferentAccess`, is that implicated too?

I'm back to I'm not really sure... but I still propose acting as if it's not a problem, and if someone reports a bug fixing it by putting code in to restore backwards compat in hashie 5, somehow.

**Comment by jrochkind** [comment]
OK no. The `IndifferentAccess` mixin does not (surprisingly) seem to depend or be depended on by the `SymbolizeKeys` mixin. And it's implementation is just `to_s`, with nothing in it checking for `to_sym` anywhere. 

https://github.com/hashie/hashie/blob/4dc015eb522abfaa2323c36024bc214ab8ccb9cc/lib/hashie/extensions/indifferent_access.rb#L29-L31

I am feeling pretty confident we're fine.

**Comment by jrochkind** [comment]
Thanks @billdueber ! I'll try to remember to do a release next week!

**Pull request merged**
