### PR TITLE
Allow nil values, empty fields, and deduplication

### PR DESCRIPTION
**Pull request by billdueber**
This adds three new settings (all of whose defaults reflect current behavior)

* `allow_nil_values` (default: false). Allow nil values to be sent on to the writer
* `allow_duplicate_values` (default: true). Allow duplicate values. Set to false to
  force only unique values.
* `allow_empty_fields` (default: false). Default behavior is that the output hash
  doesn't even contain keys for a `to_field` which doesn't produce any values.
  Set to `true` to pass empty fields on (with the value being an empty array)

Tests have been added for all the new behavior.

Updated the README and settings.md, and reorganized the latter as well.

### CODE REVIEW

**Comment by billdueber** [comment]
@jcoyne Can you take a look at this and then take it for a spin?

**Comment by billdueber** [comment]
@jcoyne pinging you one more time to see if you have any time to run this instead of your patched version and see if it'll do what you need it to do. If you don't have time, I'll just make sure my tests are all in line and push out a new version.

**Comment by jcoyne** [comment]
Sure, let me take a look.

**Comment by jcoyne** [comment]
@billdueber I don't think the readme does a good job of saying where to set those values.  I tried 
```ruby
extract_marc('650', trim_punctuation: true, allow_empty_fields: true)
```
but that obviously wasn't it.

**Comment by billdueber** [comment]
Ah, yeah. They’re settings-level things, so you set them like the other
settings.

settings do
  provide "allow_empty_fields", true
end

I can’t be turned on/off by field; is that a use case I’m missing? I was
assuming that if you have a store that needs empty fields or nil values,
you’ll have to deal with them by hand regardless of the field.
​

On Tue, Feb 23, 2016 at 9:06 PM, Justin Coyne <notifications@github.com>
wrote:

> @billdueber <https://github.com/billdueber> I don't think the readme does
> a good job of saying where to set those values. I tried
>
> extract_marc('650', trim_punctuation: true, allow_empty_fields: true)
>
> but that obviously wasn't it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject/traject/pull/126#issuecomment-188012507>.
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by jcoyne** [comment]
This is fine and it seems to work, I'm just wondering if the README should be improved.

**Comment by billdueber** [comment]
Yup. Will do. Thanks so much for the feedback.

On Tue, Feb 23, 2016 at 9:13 PM, Justin Coyne <notifications@github.com>
wrote:

> This is fine and it seems to work, I'm just wondering if the README should
> be improved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject/traject/pull/126#issuecomment-188013842>.
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by jcoyne** [comment]
Thanks for your work on this @billdueber!!! It's great to be back on master.

**Pull request merged**
