### PR TITLE
workaround for JRuby problem with regexes across threads

### PR DESCRIPTION
**Pull request by codeforkjeff**
For details, see https://groups.google.com/forum/#!msg/traject-users/v_HDAyf2NQA/vh7HBXhlFAAJ

### CODE REVIEW

**Comment by jrochkind** [comment]
Wow, nice catch and fix. Still totally don't understand what's going on -- is it an actual concurrency bug in our own code (sharing data accross threads), or a bug in jruby? 

But seems like a good fix either way. 

@billdueber , do you want to do the review/merge honors?

**Comment by billdueber** [comment]
@jrochkind @codeforkjeff I'll merge this in and release in the next day or so.

What do you guys think about dropping rbx? I'll ask the Traject list, too.

**Comment by jrochkind** [comment]
I think rbx is basically dead and nobody uses it, makes sense to me. 

On the other hand, no reason not to keep it in travis. Looks like `rvm use rbx-2` is failing, is the only reason why it's failing -- weird that that used to work and stopped working. Rvm is so not my favorite. But probably all it needs is the correct rbx argument for `rvm use` to be green again.

**Comment by jrochkind** [comment]
Travis docs specifically say `rbx-2` should be okay. Maybe something to report to travis. https://docs.travis-ci.com/user/languages/ruby/

**Comment by jrochkind** [comment]
Wait in JRuby it's not safe to use regexps in multi-threaded code?!?!

**Comment by billdueber** [comment]
There's a specific bug / set of bugs where regexps are sometimes shared across thread frames in ways they shouldn't be, mostly effecting the $-whatever variables. This is only exposed in JRuby 9x, and it's not clear what the right fix is going to be. 

The google groups link above contains a post with links to the relevant issues.

**Pull request merged**
