### PR TITLE
Switch from Travis to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by jkeck**
Had to switch `jruby-9.2.6.0` to `jruby-9.2.9.0` because `9.2.6.0` was not available on their `ubuntu-latest` image.

Not sure if that'll ultimately be an issue or not.

I think once this is in master it'll start building here, you can see this successfully build in my fork over at https://github.com/jkeck/traject/pull/1

In case you can't see the status over there:
Screen Shot 2020-11-06 at 11 27 46 AM

### CODE REVIEW

**Comment by jrochkind** [comment]
thank you! No worries about updating to latest jruby minor version, I think we do that anyway as it occurs to us. 

it's true that I can't see the status -- I'm new to Github Actions, why isn't it appearing for me on this PR? Will it appear for me once I merge to master?

**Comment by jkeck** [comment]
I _think_ that's the case.  I'm guessing since this is a PR from a fork it's not running the actions since I don't have access to this repo (it just ran automatically in the PR on my fork w/o any action on my part).

**Comment by jrochkind** [comment]
Nice nice. I have never done anything with GH Actions, so thanks for showing me how it's done! 

Is there a "badge" for Github Actions we can use to replace the travis one on the README?

**Comment by jrochkind** [comment]
Also, one thing I had started doing in travis -- scheduling a build to run once a week even without a PR happening. In slow-moving repos like this one, this lets you know if dependency updates cause a build failure, before letting them go on for weeks/months and pile up only to be advertised on the next PR. 

I guess that only works if you get email with the result of a build failure though, I'm not sure if GH actions will do that at all!

Not necessarily a pre-req for this PR being merged, but do you happen to now if that's possible with GH Actions?

**Comment by jrochkind** [comment]
OK, we do have to update the badge in the README too. Here are some instructions I'm trying to work through: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge

@jkeck , I think there may be some way in GH to give the repo owners of a PR you have made the ability to edit your branch? I can work on it if I have access, I think this week is gonna be a "work on GH actions" week for me. But I don't wanna merge with a non-functioning travis badge still in the README and without a GH actions one!

**Comment by jrochkind** [comment]
OK, I think I did it.... may have to do more work myself in additional PR's, thanks for getting me started @jkeck

**Comment by jkeck** [comment]
Sorry, you got back to it before I had a chance to respond.  I hadn't thought about the Badge (I didn't even remember it was there), and in fact noticed we have a lot of badges still pointing back at Travis for some of our internal projects, so thank you for the link (I have some things to fix locally now too).

**Comment by jrochkind** [comment]
Making the badge show up is one thing, but what to link it TO, so you can click on it to see details of the jobs... I kind of guessed and made it a link that filters to just this workflow and 'master' branch, i think that probably makes sense?

**Comment by jrochkind** [comment]
@jkeck if you have any app examples to show me that are rails apps (including engines) that use postgres, feel free to share! Working on getting other repos move dover, and that's currently where i'm hung up.

**Comment by jkeck** [comment]
Yeah, I think linking to the master branch was, in a lot of cases what we were doing w/ travis anyway (although it varied).

I think all of the apps that I can think of are using sqlite under test, but if I come across any I'll share an example.

**Pull request merged**
